### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by ErwinLiYH** [Adrakaris/guqin-jianzipu-font#1]
您好，请问这个字体如何使用在什么环境下使用呢，我下载了这个字体然后在wps里选择这个字体输入\7g/da/76之类的命令并没有什么反应

**Comment by Adrakaris** [comment]
请检查一下如果您的 ligatures（连字）是否打开了。没有连字就用不成。WPS里我不知道有没有这个功能，所以您只能自己去看了。至少Inkscape, Word, 这些可以使用连字。

（还有个小通知，我现在是用Noto Sans SC，而这个字体实在太大了，加字形比较麻烦，所以我计划换成个只有英字的字体当基础。）

**Comment by ErwinLiYH** [comment]
> 请检查一下如果您的 ligatures（连字）是否打开了。没有连字就用不成。WPS里我不知道有没有这个功能，所以您只能自己去看了。至少Inkscape, Word, 这些可以使用连字。
> 
> （还有个小通知，我现在是用Noto Sans SC，而这个字体实在太大了，加字形比较麻烦，所以我计划换成个只有英字的字体当基础。）

感谢！！

**Comment by Adrakaris** [comment]
没关系 :)

**Comment by hbstarjason2021** [comment]
@ErwinLiYH 您的问题解决了吗？是怎么解决的呢？
