### ISSUE TITLE
希望在项目中添加原字符

### ISSUE THREAD

**Issue by kidly1** [Adrakaris/guqin-jianzipu-font#2]
作者您好, 我正在做一个web端的减字谱输入demo, 我参考了市面上绝大多数的方案(包括广陵神器等等`), 您的项目是我最好的解决方案, 在开发过程中发现, 需要用到一些指法的"原字符" 比如勾 挑 抹等 比如现有字符中抹(mo "木") 只有和一 二 三 弦等配合的字符没有"原字符",不知道您是否可以在方便的时候在项目中添加一些原字符, 感谢

**Comment by Adrakaris** [comment]
好了，您所要的原字符已经放在最新的版本里，请去releases里看看。至于“拂”等新指法我后面会再去加，可以再发个issue放在这儿。

感谢支持
